import React from 'react'
import Head from 'next/head'
import styles from './Layout.module.css'

const Layout = ({ children, title = 'World Ranks' }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header className={styles.header}>World Ranks</header>

      <main className={styles.main}>
        {children}
      </main>

      <footer className={styles.footer}>
        Copyright © 2022 The World Ranks
      </footer>
    </div>
  )
}

export default Layout
