import React from 'react'
import Head from 'next/head'
import styles from './Layout.module.css'

const Layout = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        main
      </main>

      <footer className={styles.footer}>
        footer
      </footer>
    </div>
  )
}

export default Layout